INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He trabajado borracho', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He consumido drogas', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He consumido drogas (Sin querer)', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He hecho o recibido un baile erótico', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He enviado una mensaje fuerte o descarado a la persona equivocada', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He estado esposado (por cualquier motivo)', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He olido mi propia ropa interior para ver si está limpia o sucia', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He robado nada en una tienda', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He dicho el nombre equivocado durante las relaciones sexuales', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He tenido relaciones sexuales con alguien que me doblaba la edad', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He hecho un trío', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He tenido sexo más de 5 veces en una noche', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'Me he masturbado al aire libre', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'Me he exhibido por webcam', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He nadado desnudo', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'Me he liado con alguien de este grupo', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He tenido sexo en la calle', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'He tenido sexo en la playa', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'Me he masturbado pensando en la pareja de un/a amigo/a', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'Me he liado con dos personas el mismo día', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'Me he liado con alguien de mi mismo sexo.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca', 'Le he pegado a nadie.', 1);

INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca particular', '<player>, bebe si te has masturbado pensando en alguien de este grupo', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca particular', '<player>, bebe si has pillado a alguien de tu familia follando', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Yo nunca particular', '<player>, bebe si te has masturbado por aburrimiento', 1);

INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe tres tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe tres tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe tres tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe cuatro tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe cuatro tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, termina tu copa', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, termina tu copa', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe un traguito', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe un traguito', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe un traguito', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, bebe un traguito', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '<player>, <player2> te tiene que dar de beber', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '¡Todos a beber!', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', '¡Todos a beber!', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Las chicas beben tres tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Los chicos beben tres tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Los que lleven gafas beben 2 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Los que lleven lentillas beben 2 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Bebed un trago por cada tatuaje que tengáis.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Los que vayan de negro beben 4 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Para cada jugador, por cada \'a\' que tenga su nombre debe tomar un trago', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Para cada jugador, por cada \'e\' que tenga su nombre debe tomar un trago', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'El jugador a la derecha de <player> bebe dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'El jugador a la izquierda de <player> bebe dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Todos los que fuman beben 4 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Todos los que tengan pareja beben dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Todos los casados beben tres tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Todos los que tengan las uñas pintadas beben dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Bebe tres tragos si has hecho el amor en las últimas 48 horas', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Los que no se hayan duchado hoy, beben dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'El propietario de este teléfono reparte tres tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('¡Toca beber!', 'Los jugadores que no se toquen la nariz con la lengua beben 1 trago.', 1);

INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', 'El último en levantar la mano bebe 3 tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player>, menea tu culo en la cara del de tu derecha o bebe dos tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> dale un pico a <player2> o bebe 3 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> dale un pico a <player2> o bebe 3 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> el grupo elige qué prenda te tienes que quitar. Si te rajas bebes 4 tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> el grupo decide dónde le darás un beso a <player2>. O termina tu copa.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> el grupo decide dónde le darás un beso a <player2>. O termina tu copa.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> elige a dos personas para que se den un beso. Si se rajan, beben 2 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> elige a dos personas para que se den un beso. Si se rajan, beben 2 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> bebe un trago por cada persona presente con la que tendrías sexo', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> lame la mejilla de <player2> o bebe dos tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> deja que alguien escupa agua en tu cara o bebe 4 tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> publica una foto de todos jugando o bebe 4 tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player> di un trabalenguas, si fallas, bebes 4 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player>, intercambia una prenda con <player2> o bebe 4 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player>, besa en el cuello a <player2> o bebe 3 tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Reto', '<player>, di el color preferido de <player2> o bebe 2 tragos', 1);

INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'El jugador más flaco bebe un trago', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'El jugador más bajito bebe un trago', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'El más vago bebe 2 tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'El jugador más joven bebe un trago y el más viejo manda a beber un trago', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'El jugador con el pelo más largo (de la cabeza) bebe un trago', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'A la de 3 todos señalan al jugador que más liga. El más señalado bebe dos tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'A la de 3 todos señalan al jugador que ve más porno. El más señalado bebe tres tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'A la de 3 todos señalan al jugador más tardón. El más señalado bebe tres tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'Quien es el más probable que se case antes. El más votado bebe dos tragos.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('El más...', 'Quien es el más probable que haga un trío. El más votado bebe cuatro tragos.', 1);

INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Norma', '<player>, pon una norma. Si había norma, se anula.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Norma', '<player>, pon una norma. Si había norma, se anula.', 1);

INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Juego', 'Ronda de palabras encadenadas. Quien falle, bebe dos tragos', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Juego', 'Cada persona bebe un trago y lee en voz alta su último mensaje de Whatsapp. Empieza <player>.', 1);
INSERT INTO `card` (`title`, `text`, `active`) VALUES ('Juego', '<player> di la edad de cada jugador. Bebe dos tragos por cada fallo.', 1);



